# Literal restricts the action field to a fixed list of actions.
from typing import Literal

# BaseModel gives us Pydantic validation.
from pydantic import BaseModel, model_validator


class BrowserAction(BaseModel):

    # The browser operation that AURA wants to perform.
    action: Literal[
        "click",
        "type",
        "check",
        "select",
        "navigate"
    ]

    # ID generated by AURA's perception layer.
    # Example: "e1", "e2", "e5"
    element_id: str | None = None

    # Value used by actions such as type and select.
    # Example: "Abhinav Mishra" or "India"
    value: str | None = None

    # URL used when the action is navigate.
    url: str | None = None

    @model_validator(mode="after")
    def validate_action(self):

        # These actions operate on an element,
        # so an element_id must be provided.
        if self.action in [
            "click",
            "type",
            "check",
            "select"
        ]:

            if self.element_id is None:
                raise ValueError(
                    f"{self.action} action requires element_id"
                )

        # Type and select actions need a value.
        if self.action in [
            "type",
            "select"
        ]:

            if self.value is None:
                raise ValueError(
                    f"{self.action} action requires value"
                )

        # Navigate does not need an element.
        # Instead, it needs a URL.
        if self.action == "navigate":

            if self.url is None:
                raise ValueError(
                    "navigate action requires url"
                )

        return self